README.md

Also added note about reserved attributes (name)

Added "Zero PII" section

---

HTTP-API.md
README.md
example/feedback/Feedback.jsx
example/feedback/feedback.html

This example could be used to link to from the README

Add Vanilla HTML/JS feedback example

---

README.md

Typo fix and year bump

---

package.json

Accidentally published without rebuilding. Need another bump.

Bump to 1.3.1

---

src/config.ts

Use bucket DNS settings now

---

dev/app.tsx
package.json
postcss.config.js
src/default-feedback-prompt-handler.ts
src/feedback/FeedbackDialog.css
src/feedback/FeedbackDialog.tsx
src/feedback/FeedbackForm.tsx
src/feedback/index.ts
src/feedback/types.ts
src/main.ts
src/types.ts
test/usage.test.ts
webpack.config.ts

Closes BUC-1375
Closes BUC-1344
Closes BUC-1342
Closes BUC-1337

Misc changes required for internal usage

---

src/feedback/FeedbackDialog.css
src/feedback/FeedbackDialog.tsx
src/feedback/FeedbackForm.tsx
src/feedback/RadialProgress.css
src/feedback/RadialProgress.tsx
src/feedback/hooks/useAutoClose.ts
src/feedback/hooks/useTimer.ts
src/feedback/index.css

See demo: https://linear.app/bucket/issue/BUC-1420/close-success-message-after-a-timer

Close success message after a timer

---

README.md

Add CSP directive documentation

---

src/feedback/FeedbackDialog.css
src/feedback/FeedbackDialog.tsx

I made the whole plug a link.
To keep things subtle, I kept the same coloring as before - same color as normal text and 50% opacity.
I added a slight padding to make the hitbox bigger and added a slight opacity increase on hover
https://github.com/bucketco/bucket-tracking-sdk/assets/331790/3e5b2c9b-672f-462f-8dde-78a0fa0e1e48

Link the Bucket plug to bucket.co

---

FEEDBACK.md
README.md

- Use new modal screenshot in the README
- Remove documented usage of `bucket.feedback` at the top of the README

Highlight Live Satisfaction

---

package.json

Pre-patch 2.1.8-0

---

FEEDBACK.md
dev/app.tsx
src/feedback/FeedbackDialog.tsx
src/feedback/types.ts

Can use any CSS value, or a number as a pixel value.

Support offsetting feedback dialog

---

package.json

Release v2.1.11

---

src/main.ts
test/usage.test.ts

This is a repeat of https://github.com/bucketco/bucket-tracking-sdk/pull/101 which accidentally got merged into the wrong branch instead of `main`

Fix: Bucket sdk throws in segment destination when logging out

---

packages/tracking-sdk/test/flags.test.ts

the test was still doing its job, but this cleans up an error log

fix: test error causing "fetch failed"

---

packages/react-sdk/package.json
packages/tracking-sdk/package.json
yarn.lock

Release ReactSDK alpha1 and TrackingSDK to v2.3.2

ReactSDK 1.0.0-alpha.1, TrackingSDK v2.3.2

---

.gitignore

.gitignore needed updates since the monorepo refactor

gitignore: ignore test results again

---

packages/flag-evaluation/src/index.ts
packages/flag-evaluation/test/index.test.ts
packages/react-sdk/package.json

I'll create a separate ticket to just convert everything to `values` and stop using `value` all together.

fix: use of `values` with ANY_OF and $company.id

---

packages/node-sdk/package.json
packages/node-sdk/src/client.ts
packages/node-sdk/test/client.test.ts

Expose other context as separate property

---

packages/react-sdk/package.json

Align package.json with actual output file being generated

[React SDK] fix package.json

---

packages/browser-sdk/src/flags/flags.ts
packages/browser-sdk/src/flags/maskedProxy.ts
packages/browser-sdk/src/sse.ts
packages/browser-sdk/test/flags.test.ts
packages/browser-sdk/test/maskedProxy.test.ts
packages/react-sdk/package.json
packages/react-sdk/src/index.tsx
packages/react-sdk/test/usage.test.tsx

also improves React SDK testing by reducing mocking.

Fix flags in React SDK + fix "check" events for disabled flags

---

packages/flag-evaluation/package.json

Release new version of flag-evaluation with fixed rollout threshold calculation

flag-evaluation 0.0.6

---

packages/browser-sdk/src/client.ts
packages/browser-sdk/test/e2e/acceptance.browser.spec.ts
packages/browser-sdk/test/usage.test.ts
packages/react-sdk/src/index.tsx

The BrowserSDK needs to send user/company on init. Moving it out of the React SDK and into the Browser SDK.

[Browser SDK] send user/company on init

---

packages/browser-sdk/FEEDBACK.md
packages/browser-sdk/README.md
packages/browser-sdk/example/browser.html
packages/browser-sdk/example/feedback/Feedback.jsx
packages/browser-sdk/example/feedback/feedback.html
packages/browser-sdk/src/client.ts
packages/browser-sdk/test/e2e/acceptance.browser.spec.ts
packages/browser-sdk/test/e2e/feedback-widget.browser.spec.ts
packages/browser-sdk/test/init.test.ts
packages/browser-sdk/test/usage.test.ts
packages/react-sdk/src/index.tsx
packages/react-sdk/test/usage.test.tsx

Before:
```
new BucketClient(KEY,{user, company}, options)
```
Now:
```
new BucketClient({
publishableKey: KEY
user,
company,
...options
})
```

Browser SDK: Simplify constructors 

---

packages/node-sdk/README.md
packages/node-sdk/example/app.ts
packages/node-sdk/example/bucket.ts
packages/node-sdk/example/yarn.lock
packages/node-sdk/src/client.ts
packages/node-sdk/src/index.ts
packages/node-sdk/src/types.ts
packages/node-sdk/src/utils.ts
packages/node-sdk/test/client.test.ts
yarn.lock

Moved to an API with two classes: `BucketClient` and `BoundBucketClient` which is bound to a user/company for ease of use.

[NodeSDK] Simplify the API

---

packages/browser-sdk/package.json
packages/react-sdk/package.json
yarn.lock

Major bumps for both Browser and React SDK.

Browser SDK 2.0.0 + React SDK 2.0.0

---

packages/react-sdk/README.md

Improve installation instructions.

docs(ReactSDK) Installation instructions

---

packages/openfeature-browser-provider/example/package.json
packages/react-sdk/dev/nextjs-flag-demo/package.json
yarn.lock

Update `next` dependancy

---

packages/react-sdk/package.json
packages/react-sdk/vite.config.mjs
yarn.lock

Improves ease of use in Next.js.

make sure `"use client";` survives the build

---

.gitignore
packages/node-sdk/README.md
packages/node-sdk/example/app.test.ts
packages/node-sdk/example/app.ts
packages/node-sdk/example/bucket.ts
packages/node-sdk/example/package.json
packages/node-sdk/example/yarn.lock
packages/node-sdk/src/cache.ts
packages/node-sdk/src/client.ts
packages/node-sdk/src/config.ts
packages/node-sdk/src/index.ts
packages/node-sdk/src/types.ts
packages/node-sdk/src/utils.ts
packages/node-sdk/test/cache.test.ts
packages/node-sdk/test/client.test.ts
packages/node-sdk/vite.config.js

- Introduce comprehensive configuration options from environment variables and a local file.
- Introduced feature targeting overrides which are useful in testing and with local development.
- Switch logging to be `info` by default.

feat: allow external config incl. feature targeting overrides

---

packages/node-sdk/src/config.ts

Reduces buffer flush time to 10 seconds from 60 seconds.

feat(node-sdk): reduce batching to 10 seconds.

---

packages/browser-sdk/package.json
packages/openfeature-browser-provider/example/package.json
packages/openfeature-browser-provider/package.json
packages/react-sdk/dev/nextjs-flag-demo/package.json
packages/react-sdk/package.json
packages/tracking-sdk/package.json
yarn.lock

bump and publish new version when #265 has been merged 🚢

bump version for browser-facing packages using the feedback widget

---

packages/browser-sdk/package.json
packages/react-sdk/package.json
yarn.lock

Alpha pre-release of the new Toolbar, see
https://github.com/bucketco/bucket-javascript-sdk/pull/290

Bump browser and react SDK to 3.0.0-alpha.0

---

package.json
packages/openfeature-browser-provider/example/package.json
packages/react-sdk/package.json
yarn.lock

Fix various minor dependency resolution warnings

---

packages/browser-sdk/package.json
packages/react-sdk/package.json
yarn.lock

Includes https://github.com/bucketco/bucket-javascript-sdk/pull/299

Bump react + browser SDK to v3.0.0-alpha.2

---

packages/node-sdk/package.json
packages/node-sdk/src/client.ts
packages/node-sdk/src/types.ts
packages/node-sdk/test/client.test.ts

This PR adds the ability to pass the `meta` to `getFeature(s)` and the bound client.

feat(node-sdk): allow passing `meta` to `getFeature(s)`

---

packages/openfeature-browser-provider/README.md
packages/openfeature-browser-provider/package.json
packages/openfeature-browser-provider/src/index.test.ts
packages/openfeature-browser-provider/src/index.ts
yarn.lock

- Upgrade Bucket Browser SDK to 3.0.0-alpha.2
- Improve context translation with more robust type handling
- Enhance flag resolution methods with detailed error handling
- Add support for more complex object and string flag evaluations
- Update README with comprehensive documentation on flag resolution methods
- Improve test coverage for various flag resolution scenarios

feat(openfeature-web-provider): improve flag resolution and context handling

---

packages/react-sdk/package.json
packages/react-sdk/src/index.tsx

Refactor type handling for useFeature to better support different feature configurations and improve type safety

fix(react-sdk): improve type definitions for useFeature hook

---

packages/browser-sdk/package.json
packages/openfeature-browser-provider/package.json
packages/react-sdk/package.json
yarn.lock

Release new versions of the browser-sdk, react-sdk and the openfeature-browser-provider.

chore(browser-sdk,react-sdk,of-browser): 3.0.1

---

packages/openfeature-node-provider/example/app.ts
packages/openfeature-node-provider/example/serve.ts
packages/openfeature-node-provider/package.json

Missing "exports" and the existing paths were wrong. Cleaned a few additional things.

fix(of-node): update "exports" to point to the right files

---

packages/browser-sdk/package.json
packages/browser-sdk/src/toolbar/Features.css
packages/browser-sdk/src/toolbar/Switch.css
packages/browser-sdk/src/toolbar/Toolbar.css
packages/openfeature-browser-provider/package.json
packages/react-sdk/package.json
yarn.lock

Moving away from the purple color, going monochrome for the switch and blue for the dot highlight.

Update Toolbar colors and switch

---

packages/flag-evaluation/package.json
packages/node-sdk/package.json
packages/openfeature-node-provider/package.json
yarn.lock

Publishes https://github.com/bucketco/bucket-javascript-sdk/pull/426

chore(node-sdk,openfeature-node-provider): 1.8.4,0.3.2

---

packages/cli/commands/init.ts
packages/cli/package.json
packages/react-sdk/README.md

- Updated the version in package.json from 1.0.0 to 1.0.1.
- Modified the welcome message in the init command to include a symbol for branding consistency.

chore: bump CLI version to 1.0.1 and update welcome message
