.github/workflows/tests.yml, package.json, test/init.test.ts
Example report: https://github.com/bucketco/bucket-tracking-sdk/runs/6921564709?check_suite_focus=true
I used the `java-junit` reporter here because `jest-unit` [did not work ](https://github.com/bucketco/bucket-tracking-sdk/runs/6921439826?check_suite_focus=true). 
Annotations are not quite right, but i didn't find a way to fix them.
=> Move CI to GitHub actions

package.json, src/ably.ts, src/main.ts, src/prompt-storage.ts, src/prompts.ts, src/types.ts, test/ably.test.ts, test/init.test.ts, test/prompt-storage.test.ts, test/prompts.test.ts, test/usage.test.ts, vite.config.js, yarn.lock
BUC-1324 BUC-1321
- Now, properly managing the lifetime of the prompts within the SDK,
- Node.js environment is not allowed for feedback prompting (unless we later decide to enable that),
- Re-organized a number of type names to better suite us. Also, make sure to reuse the same type (user/company) across all calls,
- Testing all scenarios, including delayed prompts (in the future) and the situation where prompting is disabled with a pending future prompt (of another user's prompting is started),
- Added some additional tests to improve our coverage, seeing that this is a critically important library.
=> Life-time management of feedback prompts in the SDK

src/main.ts, test/usage.test.ts
Small correction - the prompts that have been already seen should not trigger a "received" each time the session if resumed.
=> Do not register received event if the prompt was already seen.

eslint.config.js, package.json, src/main.ts, src/types.ts, test/usage.test.ts, yarn.lock
This PR makes the calls inside the feature prompting `async` instead of creating naked promises. This will help clients to actually catch errors on submit instead of always assuming that submit was successful. Also, some internal calls do now also use `await` in order to guarantee that the signals we expect actually arrive in out tracking endpoint.
=> Use async calls instead of sync ones

dev/app.tsx, src/feedback/FeedbackDialog.tsx, src/feedback/FeedbackForm.tsx, src/feedback/StarRating.tsx, src/feedback/types.ts, src/main.ts
- Allows overriding every string in the widget
- _except_ for the "Powered by Bucket" text.
- I removed the `dimmed` of the "(optional)" text above the comment. Looks a bit less nice, but felt awkward having to provide two translation keys here
=> Support translating strings within the widget

src/feedback/FeedbackDialog.tsx
Tiny issue I noticed with the close button when submitting popover + modal forms. See the issue here: https://linear.app/bucket/issue/BUC-1475/fix-flash-of-full-radial-progress-after-submitting-feedback
=> Fix 'flash' of full radial progress after submitting feedback

src/main.ts, test/usage.test.ts
Super naive implementation. I felt a viewport check was suitable enough, given the reason we're disabling on mobile is that it needs some work on small screens.
=> Disable prompting on mobile

src/feedback/FeedbackForm.css
=> Add text-wrap balance to widget title

src/feedback/FeedbackDialog.css, src/feedback/FeedbackForm.css, src/feedback/FeedbackForm.tsx
Two minor tweaks:
- Make the widget a tad slimmer in width by default since there's a lot of blank whitespace on the right, which makes it feel very left-heavy. Cons: it makes for less space in the question before it wraps + the feedback textarea becomes a bit smaller. I think both are acceptable though as it still allows for decent length of the question before wrapping to 2+ lines.
- Increase line-height somewhat for the title and textarea to give it slightly more breathing room
https://github.com/bucketco/bucket-tracking-sdk/assets/222419/1078f2eb-73e2-4eae-aecf-df0b5ccc858d
=> Visual widget tweaks (width, line-height)

package.json, src/sse.ts, test/sse.test.ts, yarn.lock
After looking again over the implementation of `ReconnectingEventSource` I have realized we do not need any of its functionality:
* last_event_id (we do not use that),
* reconnecting on error (state 2), we do not use that as we deal with our own retry loop.
As a side bonus, added some "sanity" checks on the JSON parsing of incoming messages to avoid escaping the retry cycle even in the worst situations (unlikely that Ably will fail as such but better to be safe than sorry).
=> Remove the reconnecting event source and add some checks

README.md, src/config.ts, src/main.ts, src/sse.ts, src/types.ts, test/sse.test.ts
`init` options now take a separate `sseHost` to let users select a different host for the live connection. This is in addition the existing `host` option. Both of these are useful for proxying.
=> feat: allow custom SSE host

example/empty.html, src/main.ts, src/prompt-storage.ts, src/sse.ts, test/e2e/acceptance.browser.spec.ts, test/e2e/feedback-widget.browser.spec.ts, test/prompt-storage.test.ts, test/sse.test.ts, test/usage.test.ts
* Cache the cookie locally (for its validity time),
* Also, added cookie settings to avoid Firefox complaints: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value
=> Cache Ably auth-cookie

package.json, src/prompt-storage.ts, src/sse.ts, test/prompt-storage.test.ts, test/sse.test.ts, yarn.lock
This PR fixes an issue with cached token serialization and adds preventive fix in case a token is manually modified or possibly invalid due to server-side credential changes.
=> fix: auth cookie serialization/deserialization

package.json, src/config.ts, src/main.ts, src/sse.ts, test/usage.test.ts
We were not including the SDK version into the `/auth` call for some reason. This PR remedies that. Also re-arranged come code to make it shareable.
=> Include SDK version in the auth call and improve config

test/sse.test.ts
I had this test fail with the classic one hour timezone difference
```
FAIL  test/sse.test.ts > connection handling > does not reuse cached token with wrong channel
AssertionError: expected "spy" to be called with arguments: [ 'foo', 'channel', 'token', …(1) ]
Received:
1st spy call:
Array [
"foo",
"channel",
"token",
-   2023-01-01T00:00:00.000Z,
+   2022-12-31T23:00:00.000Z,
```
=> Fix test data mock that fails when run in a non-UTC timezone

src/main.ts, test/usage.test.ts
This changes behavior to always prefer a passed-in userId over any persisted user id.
We've seen situations where race conditions can lead to en error being thrown by our SDK when following segments recommended approach to logging out:
```
analytics.track('Signed Out');
analytics.reset();
```
The bucket SDK can be reset before the event get tracked, which currently throws because only the persisted userId is taken into account, despite segment actually providing a userId explicitly in the `bucket.event()`-call
There is a possible discussion to be had on the behavior where both a persisted userId exists and an explicit userId is passed along. In this PR I treat the userId argument as authoritative, but we might want the behavior to be preferring the persisted userId if one exists
=> Always allow userId override with explicit argument

src/main.ts, src/prompts.ts, src/types.ts
We've been using type lookup (?) which diminished readability. These types are part of the API now and they will never change so might as well use those types directly.
No types are actually changing here, just the way we write them
=> chore: Simplify types

src/config.ts, src/flags-fetch.ts
We're using a GET request to avoid CORS preflight requests for feature flags. This requires us to send the SDK version information along in a query string instead of the custom header we use for POST requests.
Updated the header/query param name to be lower-case. For headers it doesn't matter because headers are case-insensitive, but for the query param it's simpler to just have things be lower-case.
=> fix: send SDK version along with fetch requests

packages/tracking-sdk/src/flags-fetch.ts, packages/tracking-sdk/test/flags.test.ts
The behaviour on a failed response is now to:
- try and extend the expiration of the last cached response if possible
- cache the failure if not
- but always refetch on load if the cached response is a failure
=> Fix behaviour around failed FF responses

packages/react-sdk/src/index.tsx, packages/react-sdk/test/usage.test.tsx, packages/tracking-sdk/src/flags-fetch.ts
only enabled flags are returned from the API.
=> fix: do not log error if flag is simply disabled

packages/flag-evaluation/package.json
See publish failure here: https://github.com/bucketco/bucket-tracking-sdk/actions/runs/9548138256/job/26314637159#step:7:19
=> Unable to publish due to missing publish config

packages/react-sdk/README.md
I noticed we were being a bit too magical in our documentation on how to use the react sdk.
- Added import statements
- Used `BucketProvider` as a name for the default export for more clarity
=> Update react readme

packages/react-sdk/package.json, packages/tracking-sdk/package.json
After we renamed the repository, this is needed for packages to show in GitHub repositories under "Packages".
=> update "repository" in package.json

packages/tracking-sdk/src/flags-cache.ts, packages/tracking-sdk/src/flags-fetch.ts, packages/tracking-sdk/test/flags-cache.test.ts, packages/tracking-sdk/test/flags.test.ts
Requests for feature flags get cancelled if there's a page change around the same time as the flag request goes out. There's no reliable way to know if a request was cancelled or otherwise failed.
This PR changes the caching logic so we will not use a negative cached result until it's failed 3 times. If any of the first three requests succeed, that response will be used.
=> feat: allow multiple attempts to fail before caching a negative result

packages/react-sdk/src/index.tsx
If the context provider is never initialized, `isLoading` will continue to return true. This fixes that.
=> fix: default isLoading to false

packages/flag-evaluation/package.json, packages/flag-evaluation/src/index.ts, packages/flag-evaluation/test/index.test.ts
This PR removes the `async` decorator from evaluating flags as it is unnecessary. This change is required as part of other upcoming PR.
=> Remove the async decorator from evaluate (not needed)

packages/flag-evaluation/package.json, packages/flag-evaluation/src/index.ts, packages/flag-evaluation/test/index.test.ts
This PR removes the distinction between segment and context filters. This is a prerequisite for merging multiple rule types in a flag. 
Other changes will be required in 3 other projects.
=> Remove the distinction between segment and context filters.

packages/react-sdk/vite.config.mjs
Although the build process completes successfully, there's a bunch of errors regarding the Next.js example from the d.ts file generation.
=> [React SDK] exclude nextjs example when generating d.ts files

packages/react-sdk/README.md, packages/react-sdk/dev/nextjs-flag-demo/components/Flags.tsx, packages/react-sdk/dev/plain/app.tsx, packages/react-sdk/src/index.tsx, packages/react-sdk/test/usage.test.tsx
To minimize the API we're going to:
- remove `useFeatures`
- remove `useUpdateContext`: Updated example to show how to work around this if really needed
If needed, we can add them back in.
=> simplify React SDK

packages/browser-sdk/package.json, packages/react-sdk/package.json, yarn.lock
After https://github.com/bucketco/bucket-javascript-sdk/pull/176 goes in, we'll cut this new version.
=> React + Browser v1.1.0

packages/flag-evaluation/package.json, packages/flag-evaluation/src/index.ts, packages/flag-evaluation/test/index.test.ts, yarn.lock
- Rollout threshold was being used incorrectly
- We always added the `company.id` to missing context if rollout threshold wasn't 100%.
Also changed from jest to vitest to align with the other packages in the repository.
=> flag-evaluation: rollout pct logic was wrong

packages/browser-sdk/src/client.ts, packages/browser-sdk/src/feature/features.ts, packages/browser-sdk/test/features.test.ts
I kept the BucketClient API to be `otherContext`. It's a lot clearer than `other` especially since we're merging the "context" into the regular options here #189.
=> otherContext is just `other` for the API

packages/node-sdk/src/index.ts
Useful for any downstream libraries wrapping the NodeSDK.
=> chore(NodeSDK): expose Context

packages/browser-sdk/README.md
Add missing documentation detailing the difference between `getFeature` and `getFeatures`
=> [BrowserSDK]: document `getFeature` and `getFeatures`

packages/node-sdk/src/client.ts, packages/node-sdk/test/client.test.ts
`getFeatures()` was only returning enabled features which caused situations where user code would throw an error in case the feature was disabled.
This would fail because the expression on the right would be `undefined`
```ts
const {track, isEnabled} = client.getFeatures(context)["huddle"]
```
=> fix(NodeSDK): getFeatures() should return all features

packages/browser-sdk/README.md, packages/browser-sdk/src/client.ts, packages/browser-sdk/test/init.test.ts, packages/react-sdk/README.md, packages/react-sdk/src/index.tsx, packages/react-sdk/test/usage.test.tsx
In situations where you do not want to send events or track user/company details on behalf of a user but still want to use them for feature targeting, you should be able to disable it. This is useful for example when and admin is impersonating another user.
=> feat: `enableTracking` makes it possible to disable tracking

packages/node-sdk/src/client.ts, packages/node-sdk/test/client.test.ts
In offline mode:
- batchBuffer interferes because it schedules callbacks which can leave tests hanging.
- no longer necessary to call `initialize` to avoid getting a warn log.
=> fix: offline: ensure batchBuffer is not added to and no logging happens

packages/browser-sdk/src/feedback/ui/FeedbackDialog.tsx
Positioning the widget in a popover state can be tricky given the various environments that it can used in. With the current positioning where `bottom` is preferred, it can result in very crowded placements if there's very little room for it.
Before, example:
Using the `flip` middleware for floating UI, it will flip to another side when there's not enough room available in the preferred direction. It will prefer following placements, in this order: `bottom`, `top`, `right`, `left`.
After, example:
=> add autoplacement middleware

.github/workflows/package-ci.yml, packages/browser-sdk/package.json, yarn.lock
Tests are currently failing due to an updated base image which no longer
contains the playwright dependencies:
https://github.com/bucketco/bucket-javascript-sdk/actions/runs/12380013335/job/34555430888
=> chore: updating playwright

packages/browser-sdk/package.json, packages/node-sdk/package.json, packages/openfeature-browser-provider/package.json, packages/openfeature-node-provider/package.json, packages/react-sdk/package.json, yarn.lock
Following https://github.com/bucketco/bucket-javascript-sdk/pull/268,
this bumps versions of all the packages except the NodeSDK which didn't change.
=> chore: release new versions with fixed "exports"

packages/browser-sdk/package.json, packages/browser-sdk/src/client.ts, packages/browser-sdk/src/feature/features.ts, packages/flag-evaluation/package.json, packages/flag-evaluation/src/index.ts, packages/flag-evaluation/test/index.test.ts, packages/node-sdk/package.json, packages/node-sdk/src/client.ts, packages/node-sdk/src/types.ts, packages/node-sdk/test/client.test.ts, yarn.lock
Updated the Node and Browser SDKs to utilize the new `evaluateFeatureRules` method from `@bucketco/flag-evaluation@~1.0.0`. This enhances the clarity and compatibility of feature evaluation logic. Adjusted related test cases and bumped package version to 1.4.4.
=> Refactor SDK to use updated `evaluateFeatureRules` API

packages/browser-sdk/README.md, packages/browser-sdk/src/client.ts, packages/browser-sdk/src/context.ts, packages/browser-sdk/src/feature/features.ts, packages/browser-sdk/test/client.test.ts, packages/browser-sdk/test/features.test.ts, packages/react-sdk/README.md, packages/react-sdk/dev/plain/app.tsx, packages/react-sdk/package.json, packages/react-sdk/src/index.tsx, packages/react-sdk/test/usage.test.tsx, yarn.lock
This introduced methods to let you update the user/company/other context after initialization. This lets you easily update data when it changes without needing to re-initialize etc. Useful for example to let users self opt-in to experimental features.
The PR also introduces some plumming needed to make sure that any changes that happen to feature targeting after you update the user/company/other is reflected, live, in the `useFeature` calls you have in your code.
=> Introduce methods to update context after intialization

packages/browser-sdk/package.json, packages/node-sdk/README.md, packages/node-sdk/package.json, packages/node-sdk/src/client.ts, packages/node-sdk/src/config.ts, packages/node-sdk/src/types.ts, packages/node-sdk/test/client.test.ts, packages/node-sdk/test/config.test.ts, packages/node-sdk/test/testConfig.json, packages/react-sdk/package.json, packages/react-sdk/src/index.tsx, packages/react-sdk/test/usage.test.tsx, yarn.lock
Replaced the `host` property with `apiBaseUrl` across all SDKs for improved clarity and consistency. Updated tests, documentation, and implementation to reflect the change while marking `host` as deprecated for backward compatibility. Bumped versions to indicate non-breaking minor changes.
=> Update SDKs to use `apiBaseUrl` instead of `host`

.vscode/settings.json, packages/browser-sdk/README.md, packages/browser-sdk/src/client.ts, packages/node-sdk/README.md, packages/node-sdk/src/types.ts
- Updated README files to document new `avatar` attribute
- Added `avatar` to user and company context types in browser and node SDKs
- Expanded documentation for special attributes in context objects
- Added type definitions for avatar in relevant type files
=> feat(browser-sdk,node-sdk): add avatar support for user and company contexts

packages/node-sdk/package.json, packages/node-sdk/src/batch-buffer.ts, packages/node-sdk/src/cache.ts, packages/node-sdk/src/rate-limiter.ts
Unable to write a test for this, but tested manually.
=> fix(node-sdk): ensure timers don't keep process alive

.github/workflows/publish.yml
Since `main` has gone to 1.6-alpha, we need to start a separate branch for 1.5 series releases. This'll let us run the publish script from any branch that starts with `v` as in `v1.5`.
=> chore: auto-publish in "v*" branches

packages/browser-sdk/package.json, packages/react-sdk/package.json, yarn.lock
No-op release to fix NPM release tag in which latest points to a prerelease by mistake.
Node.js "latest" pointing to a prerelease was fixed here: https://github.com/bucketco/bucket-javascript-sdk/commit/579eb1c2d848e17fb127a6ee73c6529f6e470b89
=> chore(browser-sdk,node-sdk): version 2.5.2

packages/browser-sdk/src/client.ts, packages/browser-sdk/src/feature/features.ts, packages/browser-sdk/test/e2e/acceptance.browser.spec.ts, packages/browser-sdk/test/e2e/feedback-widget.browser.spec.ts, packages/browser-sdk/test/features.test.ts, packages/browser-sdk/test/init.test.ts, packages/browser-sdk/test/mocks/handlers.ts, packages/node-sdk/example/serve.ts, packages/react-sdk/test/usage.test.tsx
This removes the need to pass in a feature list to the SDK in order for features to show up in the toolbar. Instead, we'll use the `/features/evaluated` endpoint which returns all features.
=> feat: use remote feature list instead of locally defined list

packages/openfeature-node-provider/README.md, packages/openfeature-node-provider/package.json, packages/openfeature-node-provider/src/index.test.ts, packages/openfeature-node-provider/src/index.ts, yarn.lock
- Enhanced flag resolution methods with more robust error handling
- Added support for more context attributes in context translator
- Improved type checking and resolution for different flag types
- Updated README with more detailed usage and resolution method explanations
- Bumped node-sdk dependency to 1.6.0-alpha.3
=> feat(openfeature-node-provider): improve flag resolution and context handling

packages/node-sdk/README.md, packages/node-sdk/example/bucket.ts, packages/node-sdk/example/serve.ts, packages/node-sdk/package.json, packages/node-sdk/src/client.ts, packages/node-sdk/src/config.ts, packages/node-sdk/src/flusher.ts, packages/node-sdk/src/types.ts, packages/node-sdk/src/utils.ts, packages/node-sdk/test/client.test.ts, packages/node-sdk/test/flusher.test.ts, packages/node-sdk/test/utils.test.ts
This PR Introduces `flushOnExit` option in batch buffer configuration. When on (default), the client will flush all events on it's exit.
=> feat(node-sdk): add configurable exit event flushing

package.json, yarn.lock
New version has a fix I made for links to project documents.
https://github.com/typedoc2md/typedoc-plugin-markdown/blob/main/packages/typedoc-plugin-markdown/CHANGELOG.md#442
=> chore: upgrade typedoc-plugin-markdown

packages/react-sdk/src/index.tsx
If you use `useFeature` or any of the other hooks that rely on the BucketProvider without actually installing the Provider we should complain loudly. I went for throwing an error when the provider is missing because it's a serious mistake and should show up loudly as part of the development workflow:
=> fix(react-sdk): throw error on missing provider

packages/browser-sdk/README.md, packages/browser-sdk/example/typescript/app.ts, packages/browser-sdk/index.html, packages/browser-sdk/src/client.ts, packages/browser-sdk/src/feature/features.ts, packages/browser-sdk/src/hooksManager.ts, packages/browser-sdk/src/index.ts, packages/browser-sdk/src/toolbar/Toolbar.tsx, packages/browser-sdk/test/client.test.ts, packages/browser-sdk/test/hooksManager.test.ts, packages/browser-sdk/test/usage.test.ts, packages/react-sdk/src/index.tsx, packages/react-sdk/test/usage.test.tsx
Hooks allow capturing different events that happen in the Browser SDK.
They are useful for a number of things like building client side integrations to analytics or error-logging systems.
=> feat(browser-sdk): Event listeners

packages/openfeature-browser-provider/example/app/featureManagement.ts, packages/openfeature-browser-provider/example/components/HuddleFeature.tsx, packages/openfeature-browser-provider/package.json, yarn.lock
Update example to demonstrate fallback features with the Bucket OpenFeature provider, including:
- Add fallback configuration for the huddle feature
- Enhance HuddleFeature component to display provider and join URL
- Update browser SDK dependency to 3.0.0-alpha.4
=> feat(openfeature-browser-provider): add fallback features and improve huddle feature example

packages/openfeature-node-provider/example/app.ts, packages/openfeature-node-provider/example/bucket.ts
- Added support for configurable todo creation with max length validation
- Updated feature flag names to be more consistent (e.g., "show-todos", "create-todos")
- Implemented feature configuration retrieval for todo creation
- Added type definition for create todos configuration
- Improved feature tracking and error handling in todo operations
=> feat(openfeature-node-provider): enhance todo feature management with config and validation

packages/react-sdk/README.md, packages/react-sdk/package.json, packages/react-sdk/src/index.tsx, packages/react-sdk/test/usage.test.tsx
- Introduce `onFeaturesUpdated` callback in BucketProvider to allow custom handling of feature updates
- Add new `useClient()` hook to access the BucketClient directly
- Refactor hooks to use `useClient()` for simplified client access
- Update README with documentation for new features
=> feat(react-sdk): add onFeaturesUpdated prop and useClient hook

packages/browser-sdk/index.html, packages/browser-sdk/package.json, packages/browser-sdk/src/toolbar/Features.css, packages/browser-sdk/src/toolbar/Features.tsx, packages/browser-sdk/src/toolbar/Toolbar.css, packages/browser-sdk/src/toolbar/Toolbar.tsx, packages/browser-sdk/src/ui/Dialog.tsx, packages/react-sdk/package.json, yarn.lock
https://github.com/user-attachments/assets/9d45f398-933e-4b05-9e7f-5bda3f5599f8
https://github.com/user-attachments/assets/b8e1b30b-5384-42bc-9ad7-7a380d48375b
- added stagger animation for feature rows
- toolbar button and popover is now semi-transparent background with blurred glass effect
- tweaked borders to be inset shadows instead
- made toolbar button round
- fixed single pixel resizing when showing Reset
=> Small toolbar polish

packages/node-sdk/package.json, packages/node-sdk/src/client.ts, packages/node-sdk/src/types.ts, packages/node-sdk/test/client.test.ts
- Add support for tracking rule evaluation results and missing context fields,
- Improve feature flag event details in `sendFeatureEvent`,
- Update types to include new evaluation metadata
- Enhance test coverage for new event tracking features,
- Bump package version to 1.5.4
=> feat(node-sdk): enhance feature evaluation with detailed event tracking

packages/browser-sdk/README.md, packages/react-sdk/README.md, packages/react-sdk/dev/plain/app.tsx
- Simplified the getting started instructions
- Cleaned up outdates "features update" instructions. There's "Event listeners" instead.
- Update docs to reflect that `featureOptions` are passed at the root level now
=> docs(react-sdk,browser-sdk): updated various out-of-date docs

packages/browser-sdk/playwright.config.ts
Setting a port will make playwright wait until the server is listening
=> fix(browser-sdk): fix e2e test stability

packages/browser-sdk/README.md, packages/browser-sdk/src/client.ts, packages/browser-sdk/src/feature/features.ts
We'll be moving exposing feature overrides through what is returned from the `getFeature()` call rather than exposing it directly on the client.
=> docs(browser-sdk): make feature overrides internal for now

packages/cli/README.md, packages/cli/commands/features.ts, packages/cli/commands/init.ts, packages/cli/commands/new.ts, packages/cli/package.json, packages/cli/schema.json, packages/cli/stores/config.ts, packages/cli/utils/constants.ts, packages/cli/utils/options.ts
=> Publish package CLI

packages/browser-sdk/README.md, packages/browser-sdk/index.html, packages/browser-sdk/package.json, packages/browser-sdk/src/client.ts, packages/browser-sdk/src/hooksManager.ts, packages/browser-sdk/test/client.test.ts, packages/browser-sdk/test/hooksManager.test.ts, packages/openfeature-browser-provider/package.json, packages/react-sdk/README.md, packages/react-sdk/package.json, packages/react-sdk/src/index.tsx, yarn.lock
- Deprecate enabledCheck and configCheck event listeners in favour of just `check`.
- Publishes new patch version for browser and react sdks.
=> fix:(browser-sdk,react-sdk): consolidated specific enabled/config check listeners

packages/cli/commands/apps.ts, packages/cli/commands/auth.ts, packages/cli/commands/features.ts, packages/cli/commands/init.ts, packages/cli/commands/new.ts, packages/cli/package.json, packages/cli/services/features.ts, packages/cli/services/stages.ts, packages/cli/utils/auth.ts, packages/cli/utils/gen.ts, packages/node-sdk/package.json, packages/node-sdk/src/types.ts
- Added stages export as a simple union `export type Stage = "Alpha" | "Beta";`.
- Fix node-sdk type to match react-sdk.
- Improved type gen logging.
- Made all logging more consistent.
=> feat: fix node type, add stages, cleanup logs

packages/browser-sdk/README.md, packages/react-sdk/README.md
=> docs(react-sdk,browser-sdk): Improve toolbar docs

packages/cli/README.md, packages/cli/commands/apps.ts, packages/cli/commands/features.ts, packages/cli/commands/init.ts, packages/cli/commands/new.ts, packages/cli/index.ts, packages/cli/package.json, packages/cli/schema.json, packages/cli/services/bootstrap.ts, packages/cli/services/features.ts, packages/cli/stores/config.ts, packages/cli/utils/auth.ts, packages/cli/utils/constants.ts, packages/cli/utils/errors.ts, packages/cli/utils/gen.ts, packages/cli/utils/options.ts, packages/cli/utils/path.ts, yarn.lock
By adding a call to bootstrap we can improve the logging of the CLI.
https://github.com/user-attachments/assets/9ccac815-84da-4591-b4e1-cca86ccb5944
=> feat: improve logging by fetching bootstrap first

packages/cli/commands/auth.ts, packages/cli/package.json, packages/cli/utils/auth.ts, packages/cli/utils/constants.ts, packages/cli/utils/path.ts
This authentication flow does not use a fetch request to `http://localhost` but instead redirects there. We don't want to pass the actual access token along so it becomes part of the browser history. Instead we supple a code which is then exchanged for the actual access token through a new API endpoint in the backend.
This starts to look very much like a standard oauth flow. The key missing piece is come `client_id` parameters. I'm making the new server endpoints live under `/api/oauth/cli` so that when we do introduce propert oauth there will be no clashes.
I removed the spinner on login because it indicates that it's working when in reality it's waiting for you to do something. I'm also printing out the URL in case opening of the browser doesn't work.
=> feat: use new login scheme which supports Safari

README.md, packages/cli/utils/errors.ts, packages/node-sdk/README.md, packages/react-sdk/README.md
This updates the default workflow for React to use the CLI to remove friction and generate types. 
The Node.js docs still need some more love, but this is a start.
=> docs(cli,react-sdk,node-sdk): Introduce the CLI for type gen

packages/node-sdk/package.json, packages/node-sdk/src/types.ts, packages/react-sdk/package.json, packages/react-sdk/src/index.tsx
Utilizing [TypeScript intersection](https://github.com/microsoft/TypeScript/pull/31838) to simplify config types. Config keys and payload can now always be `undefined`.
=> feat: simplify types treating key and payload always as optional

packages/react-sdk/package.json, packages/react-sdk/src/index.tsx, packages/react-sdk/test/usage.test.tsx
=> fix(react-sdk): reset loading state when context updates

packages/flag-evaluation/package.json, packages/flag-evaluation/src/index.ts, packages/flag-evaluation/test/index.test.ts, packages/node-sdk/src/index.ts, packages/node-sdk/src/types.ts, yarn.lock
Since `digest` is async, we need to update the interface to be async.
=> feat: use webcrypto API to support edge runtimes

packages/node-sdk/package.json, packages/node-sdk/src/client.ts, packages/node-sdk/src/config.ts, packages/node-sdk/src/fetch-http-client.ts, packages/node-sdk/src/types.ts, packages/node-sdk/test/client.test.ts
Our HTTP API responds to `/feature` requests in less than 5ms, but there are cases where the network on the client could be dodgy or there's otherwise some delay. Especially when the program is just starting up this is problematic because the NodeSDK will use the fallback flags which for the most part are empty.
This introduces a configurable timeout and default the timeout to 10s instead of the existing 5s. It also adds an exponential retry which is set to 3 tries by default.
=> fix(node-sdk): increase default `get` timeout to 10s, add 3 retries

packages/cli/mcp/tools.ts, packages/cli/package.json, packages/cli/services/companies.ts
=> fix(cli): minor MCP updates

packages/node-sdk/package.json, yarn.lock
This is required to make the NodeSDK work on edge runtimes. Needs #390 to go in first.
=> fix(node-sdk): use `flag-evaluation` which falls back to pure js crypto

packages/cli/index.ts, packages/cli/package.json, packages/cli/utils/commander.ts
This pull request introduces several changes to the CLI package to improve command handling and versioning. The key updates include adding a utility function for command names, skipping bootstrap for specific commands, and updating the package version.
* [`packages/cli/index.ts`](diffhunk://#diff-ce752ce36be970cbc0110dae521e82462b9ee7dbca55f45b51648c82998da18dR17-R23): Added `commandName` import and defined `skipBootstrapCommands` to skip bootstrapping for certain commands. Updated `preAction` hook to check command names and conditionally skip bootstrapping. [[1]](diffhunk://#diff-ce752ce36be970cbc0110dae521e82462b9ee7dbca55f45b51648c82998da18dR17-R23) [[2]](diffhunk://#diff-ce752ce36be970cbc0110dae521e82462b9ee7dbca55f45b51648c82998da18dL38-R41) …
=> fix: skip bootstrap for specific commands

packages/node-sdk/src/cache.ts, packages/node-sdk/src/client.ts, packages/node-sdk/src/fetch-http-client.ts, packages/node-sdk/test/client.test.ts
- removed `unref()` to ensure retries block the process from exiting
- improved logging around retries
=> fix: improved retry logic, improve retry logging

packages/node-sdk/src/client.ts, packages/node-sdk/test/client.test.ts
Correctly initializing the BucketClient can be a bit tricky. This should complain more loudly when it happens.
I considered and rejected the idea of throwing an error when this happens because incorrectly constructed initialization code may only break under high concurrency and thus only show up in production which could cause down time if we throw.
=> fix: Improve logging when not initialized

packages/browser-sdk/src/client.ts, packages/browser-sdk/src/toolbar/Features.tsx, packages/browser-sdk/src/toolbar/Toolbar.tsx, packages/browser-sdk/test/client.test.ts, packages/browser-sdk/test/usage.test.ts, packages/react-sdk/dev/plain/app.tsx
includes new example of how to make your own toolbar.
https://github.com/user-attachments/assets/7195ac69-a1c4-4508-b232-01c3230513b5
=> refactor(browser-sdk): refactor overrides API

packages/browser-sdk/README.md
- Removed outdated Beta label
- Moved Toolbar up
- Removed Feedback image (as it's on the subpage)
=> Remove Beta and reordering

packages/flag-evaluation/package.json, packages/flag-evaluation/src/index.ts, packages/flag-evaluation/test/index.test.ts, yarn.lock
- Refined evaluation logic for "SET" and "NOT_SET" operators to use strict equality checks.
- Added tests to ensure correct behavior for missing context fields with "SET" and "NOT_SET" operators, including handling empty string values.
=> chore(flag-evaluation): improve SET/NOT_SET operator evaluations

packages/node-sdk/src/client.ts, packages/node-sdk/src/types.ts, packages/node-sdk/test/client.test.ts
Use the new facility from the `flag-evaluation` package to ensure low CPU even with huge lists of targets.
=> feat(node-sdk): use optimized flag evaluation

packages/flag-evaluation/package.json, packages/flag-evaluation/src/index.ts, packages/flag-evaluation/test/index.test.ts, packages/node-sdk/package.json, packages/openfeature-node-provider/package.json, yarn.lock
- Bumped version of `@bucketco/flag-evaluation` to 0.2.0 and added new context filter operators: `DATE_AFTER` and `DATE_BEFORE`.
- Updated `@bucketco/node-sdk` to 1.9.0 to reflect the new version of `@bucketco/flag-evaluation`.
- Updated `@bucketco/openfeature-node-provider` to use the latest `@bucketco/node-sdk` version.
=> feat: add new context filter operators

packages/node-sdk/package.json, packages/node-sdk/src/client.ts, packages/node-sdk/src/types.ts, packages/node-sdk/test/client.test.ts, packages/openfeature-node-provider/package.json, yarn.lock
This PR adds a new `emitEvaluationEvents` option (default: `true`). When set to`false`, the node SDK will not generate `evaluate` and `evaluate-config` events.
=> feat: allow disabling "evaluate" event generation

.github/workflows/publish.yml
- Changed the repository reference from `bucketco/docs` to `reflag/docs`.
- Updated the path for the checked-out documentation from `bucket-docs` to `reflag-docs`.
=> fix: update GitHub Actions workflow for documentation repository

.github/workflows/publish.yml, .vscode/settings.json
- Changed the repository reference from `reflag/docs` to `reflagcom/docs`.
- Updated the spelling of `reflag` to `reflagcom` in VSCode settings for spell checking.
=> fix: update documentation repository reference in GitHub Actions workflow
